POST http://localhost:8081/anime/
Content-Type: application/json

{
    "title":"Death Note",
    "description":"Loco Asesino",
    "chapters":[
        {
            "name":"capitulo 1"
        }
    ],
    "category":"Terror"
}